remote_theme: daattali/beautiful-jekyll
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

title: Jeyong Sohn
author: Jeyong Sohn


navbar-links:
  
  Bio: "bio"
  Research: "research"
  Teaching: "teaching"
  Blog: "blog"

avatar: "/assets/img/uni.png"

social-network-links:
  email: "sohn@rikkyo.ac.jp"
  github: sjeyong
  twitter: jeyongs
 
share-links-active:
  twitter: true
  facebook: true
  linkedin: true

excerpt_length: 50
feed_show_excerpt: false
feed_show_tags: false

keywords: "political,science"

link-col: "#404040"

mobile-theme-col: "#0085A1"

site-css: "/assets/css/custom-styles.css"
site-js: "/assets/js/custom-script.js"

timezone: "Asia/Seoul"
permalink: /blog/:title/
paginate: 10
paginate_path: "/page:num/"


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      carbonads: False
      comments: true
      social-share: true
      show-share: true
      show-subscribe: false
      support_promo_box: false
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "notblog"
    values:
      layout: "post"
      carbonads: false
      comments: true
      social-share: true
      show-share: true
      show-subscribe: false
      support_promo_box: false
      after-content: [share-section.html, scroll-box.html]
  -
    scope:
      path: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "page"
      before-content: false
      footer-extra: false

exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - docs/
  - files/java/Scrabble/*

# 2fc73a3a967e97599c9763d05e564189d5
